class BlockTok;
class Expression;
class Statement;
class Symbol;
class SymbolType;
class DoubleLinkList;
class Buffer;
class Tawk;
class PLGitem;
/*******************************************************************************
        The Instance class captures a reference to a syntax element that can be
		a cast, symbol, expression, statement, block, type or constant.
*******************************************************************************/

class Instance
{
public:
BlockTok *block;
Expression *express;
Statement *statement;
Symbol *symbol;
SymbolType *type;
Instance *cast;
Instance *format;
Instance *parent;
int instanceIndex;
int level;
struct 
	{
	unsigned int arrayRef:4;
	unsigned int assigning:1;
	unsigned int atString:1;
	unsigned int checked:1;
	unsigned int emitted:1;
	unsigned int hasBranch:1;
	unsigned int indirection:4;
	unsigned int isCase:1;
	unsigned int isCast:1;
	unsigned int isComment:1;
	unsigned int isCondition:1;
	unsigned int isConstant:1;
	unsigned int isCopy:1;
	unsigned int isDeclaration:1;
	unsigned int isError:1;
	unsigned int isExternalType:1;
	unsigned int isLabel:1;
	unsigned int isLambda:1;
	unsigned int isLocal:1;
	unsigned int isMethod:1;
	unsigned int isNew:1;
	unsigned int isPrintMethod:1;
	unsigned int isRange:1;
	unsigned int isSelector:1;
	unsigned int noBody:1;
	unsigned int noGetter:1;
	unsigned int reference:4;
	unsigned int requalified:1;
	unsigned int resolved:1;
	unsigned int terminated:1;
	unsigned int virtuous:1;
	unsigned int isUsed:1;
	};
char *prefix;
char *postfix;
DoubleLinkList *parameters;
static int instanceCount;
static Symbol *objectiveCsend;
Instance();
Instance(SymbolType *t);
Instance(Symbol *s);
Instance(char *s);
Instance(Statement *s);
Instance(Instance *i);
Instance(Expression *e);
Instance(BlockTok *b);
void addParameter(Instance *parameter);
void addPostFix(char *s);
void addPrefix(char *s);
Instance *castAlias();
void check();
void checkBracketEqual();
Instance *checkCast(Instance *target);
Instance *checkCast(Symbol *target);
Instance *checkOverload();
void checkSymbol();
void convertMethod();
Instance *copyAndSetParent(Instance *instance);
void dump();
void error(char *text);
Instance *findGetterOrSetter(char *name);
void fixExtension();
BlockTok *getBlock();
char *getCast();
void getCast(Buffer *buffer);
Symbol *getCompareMethod(Instance *object);
int getDirect();
Instance *getFormat();
char *getName();
char *getQualifiedName();
Instance *getSubject();
Symbol *getSymbol();
SymbolType *getType();
char *getTypeName();
char *getValue();
int hasNoBody();
int howDirect();
void insertParentAsParameter();
int instanceOC();
int isBlockStatement();
int isVirtuous();
int isVoidPointer();
char *mangle();
char *pointerName();
int qualified();
void setDefaults(Tawk *tok);
Instance *setIndirectItem(PLGitem *direct);
void setIsUsed();
void setLevel();
void setParent(Instance *instance);
void setRefer();
void setReference(int flag);
SymbolType *sourceType();
char *toString();
};
