class SymbolType;
class Symbol;
class FormatC;
class BlockTok;
class Buffer;
class BaseHash;
class Instance;
class InstanceTable;
class Operate;
class PLGitem;
class PLGset;
class Stak;
class KeyTable;
class Expression;
class PLGtester;
/*****************************************************************************
	Tawk class definition
*****************************************************************************/

class Tawk : public PLGparse
{
public:
SymbolType *currentClass;
SymbolType *currentType;
SymbolType *expressType;
SymbolType *methodType;
SymbolType *newType;
Symbol *currentMethod;
Symbol *lambdaMethod;
FormatC *formatter;
int componentCount;
int iterating;
int stringNumber;
BlockTok *currentBlock;
Buffer *tokJunkBuffer;
BaseHash *includedFiles;
BaseHash *macroHash;
BaseHash *macroList;
BaseHash *missingMethods;
Instance *defaultPrinter;
Instance *debugInstance;
Instance *virtualItem;
InstanceTable *currentSymbols;
Operate *commaOp;
PLGitem *currentComment;
PLGitem *virtualOp;
PLGset *lambdaSet;
Stak *blockStack;
Stak *switchStack;
Stak *virtualStack;
SymbolType *saveStruct;
SymbolType *saveType;
Symbol *falseSymbol;
Symbol *nullSymbol;
Symbol *trueSymbol;
char *directivesFile;
char *macroDelimiter;
struct 
	{
	unsigned int assigning:1;
	unsigned int assuming:1;
	unsigned int constDeclare:1;
	unsigned int debugging:1;
	unsigned int declaringMethod:1;
	unsigned int declaredSomething:1;
	unsigned int extending:1;
	unsigned int isQualified:1;
	unsigned int linkage:3;
	unsigned int noLoop:1;
	unsigned int noShortcuts:1;
	unsigned int parsingDirective:1;
	unsigned int processingParameters:1;
	unsigned int produceCodeFile:1;
	unsigned int referring:1;
	unsigned int stringing:1;
	};
#define externDeclare(button) (button == 1)
#define inlineDeclare(button) (button == 2)
#define staticDeclare(button) (button == 3)
#define virtualDeclare(button) (button == 4)
void *externalENV;
PLGset *alphaSet;
PLGset *nameStartSet;
PLGset *commentSet;
PLGset *compareSet;
PLGset *compareFollow;
PLGset *logicSet;
PLGset *methodSet;
PLGset *methodNameSet;
PLGset *nameSet;
PLGset *operatorSet;
PLGset *space;
PLGset *rangeSet;
PLGset *stringOP;
PLGset *textFollow;
PLGset *typesSet;
KeyTable *Attributes;
KeyTable *Conditions;
KeyTable *ReservedWord;
KeyTable *Comparisons;
KeyTable *Directives;
KeyTable *Linkage;
KeyTable *Operators;
KeyTable *Ranges;
KeyTable *State;
KeyTable *Structures;
PLGset *singleQuote;
Tawk();
void checkConversion(Expression *express);
Instance *concatenate(PLGitem *source);
Expression *convertRangeX(Instance *field, Instance *rangeField);
Instance *convertToString(Instance *source);
char *extractComment();
Instance *findInitializer(Symbol *symbol);
Instance *generatePrint(Instance *argument);
Instance *getInstance(char *text);
void initializeKeyWords();
void initializeSetTable();
Instance *makeError(char *text);
Expression *makeExpress(Instance *instance, PLGitem *item);
void popVirtuals();
void process(char *name);
void processDirectives();
Instance *processPrintTarget(PLGitem *target);
void pushVirtuals();
void resetVirtuals();
PLGitem *run(char *name);
static void setComparisons();
void setCurrentClass(SymbolType *t);
void setCurrentType(SymbolType *t);
void setOperators();
void setPrintMethods();
void setRules();
void summaryDebug();
};
int AliasItem2TawkNow(PLGitem *iTEM);
int AliasItem4TawkNow(PLGitem *iTEM);
int AliasItemTawkNow(PLGitem *iTEM);
int AllowShortcutsTawkNow(PLGitem *iTEM);
int ArrayInitializerTawkNow(PLGitem *iTEM);
int AssumedStringTawkNow(PLGitem *iTEM);
int AssumingTawkNow(PLGitem *iTEM);
int BlockStartTawkNow(PLGitem *iTEM);
int BlockTawkNow(PLGitem *iTEM);
int Body2TawkNow(PLGitem *iTEM);
int Body3TawkNow(PLGitem *iTEM);
void ButtonArrayTawkAct(PLGitem *iTEM);
int Case2TawkNow(PLGitem *iTEM);
int Case3TawkNow(PLGitem *iTEM);
int CaseLabel2TawkNow(PLGitem *iTEM);
int CaseLabel3TawkNow(PLGitem *iTEM);
int CaseLabel5TawkNow(PLGitem *iTEM);
int CaseLabelTawkNow(PLGitem *iTEM);
int CaseTawkNow(PLGitem *iTEM);
int CastExpressionTawkNow(PLGitem *iTEM);
int CastTailTawkNow(PLGitem *iTEM);
int CastTypeTawkNow(PLGitem *iTEM);
int CharacterTawkNow(PLGitem *iTEM);
int CheckMacroParametersTawkNow(PLGitem *iTEM);
int CheckMacroTawkNow(PLGitem *iTEM);
void ClassAttributes2TawkAct(PLGitem *iTEM);
void ClassAttributes3TawkAct(PLGitem *iTEM);
void ClassAttributes4TawkAct(PLGitem *iTEM);
void ClassAttributesTawkAct(PLGitem *iTEM);
int ClassBlockStartTawkNow(PLGitem *iTEM);
int ClassBlockTawkNow(PLGitem *iTEM);
int ClassHeading2TawkNow(PLGitem *iTEM);
int ClassHeading3TawkNow(PLGitem *iTEM);
int ClassHeadingTawkNow(PLGitem *iTEM);
int ClassNameTawkNow(PLGitem *iTEM);
int CommentTawkNow(PLGitem *iTEM);
int ConditionLabelTawkNow(PLGitem *iTEM);
void ConditionWordTawkAct(PLGitem *iTEM);
int Constant4TawkNow(PLGitem *iTEM);
int Constant5TawkNow(PLGitem *iTEM);
void DebugDirectiveTawkAct(PLGitem *iTEM);
int DebugRuleTawkNow(PLGitem *iTEM);
int DebugTextTawkNow(PLGitem *iTEM);
void Declaration2TawkAct(PLGitem *iTEM);
void DeclarationTawkAct(PLGitem *iTEM);
void DeclareItem2TawkAct(PLGitem *iTEM);
void DeclareItem3TawkAct(PLGitem *iTEM);
void DeclareItemTawkAct(PLGitem *iTEM);
int DeclareTypeTawkNow(PLGitem *iTEM);
int DirectiveTawkNow(PLGitem *iTEM);
int Else2TawkNow(PLGitem *iTEM);
int ExpressListTawkNow(PLGitem *iTEM);
int ExpressPartTawkNow(PLGitem *iTEM);
int ExpressTypeTawkNow(PLGitem *iTEM);
int ExpressionTawkNow(PLGitem *iTEM);
int ExtenderTawkNow(PLGitem *iTEM);
int ExtendsTawkNow(PLGitem *iTEM);
void FieldBody2TawkAct(PLGitem *iTEM);
int FieldBody3TawkNow(PLGitem *iTEM);
void FieldBodyTawkAct(PLGitem *iTEM);
int FieldExpressionTawkNow(PLGitem *iTEM);
int FieldTawkNow(PLGitem *iTEM);
int FieldingTawkNow(PLGitem *iTEM);
int FileNameTawkNow(PLGitem *iTEM);
int ForOption2TawkNow(PLGitem *iTEM);
int ForOptionTawkNow(PLGitem *iTEM);
int Include2TawkNow(PLGitem *iTEM);
int Include3TawkNow(PLGitem *iTEM);
int IncludeTawkNow(PLGitem *iTEM);
int Inheritance4TawkNow(PLGitem *iTEM);
int InitExpressionTawkNow(PLGitem *iTEM);
int InitializerItemTawkNow(PLGitem *iTEM);
int InitializerTawkNow(PLGitem *iTEM);
int InstanceTailTawkNow(PLGitem *iTEM);
int ItemHeadTawkNow(PLGitem *iTEM);
int IteratingTawkNow(PLGitem *iTEM);
int Lambda2TawkNow(PLGitem *iTEM);
int LambdaNameTawkNow(PLGitem *iTEM);
int LambdaTawkNow(PLGitem *iTEM);
int Line3TawkNow(PLGitem *iTEM);
int LineByLineTawkNow(PLGitem *iTEM);
int LineTawkNow(PLGitem *iTEM);
int MacroBitTawkNow(PLGitem *iTEM);
int MacroBlockTawkNow(PLGitem *iTEM);
int MacroBodyTawkNow(PLGitem *iTEM);
int MacroDefineTawkNow(PLGitem *iTEM);
int MacroDelimitTawkNow(PLGitem *iTEM);
int MacroNameTawkNow(PLGitem *iTEM);
void MethodHeadTawkAct(PLGitem *iTEM);
int MethodNameTawkNow(PLGitem *iTEM);
int MethodTawkNow(PLGitem *iTEM);
void MethodTypeTawkAct(PLGitem *iTEM);
int MethodTypeTawkNow(PLGitem *iTEM);
int NameTawkNow(PLGitem *iTEM);
void NewTawkAct(PLGitem *iTEM);
int NoShortcutsTawkNow(PLGitem *iTEM);
int Number2TawkNow(PLGitem *iTEM);
int NumberTawkNow(PLGitem *iTEM);
int OperationTail2TawkNow(PLGitem *iTEM);
int OperationTailTawkNow(PLGitem *iTEM);
int Operator2TawkNow(PLGitem *iTEM);
int OperatorTawkNow(PLGitem *iTEM);
int OverLoadItem2TawkNow(PLGitem *iTEM);
int OverLoadItem3TawkNow(PLGitem *iTEM);
int OverLoadItem4TawkNow(PLGitem *iTEM);
int OverLoadItem5TawkNow(PLGitem *iTEM);
int OverLoadItemTawkNow(PLGitem *iTEM);
void ParameterItem2TawkAct(PLGitem *iTEM);
void ParameterItem3TawkAct(PLGitem *iTEM);
void ParameterItem4TawkAct(PLGitem *iTEM);
void ParameterItemTawkAct(PLGitem *iTEM);
int ParameterTawkNow(PLGitem *iTEM);
int PoundCommandTawkNow(PLGitem *iTEM);
int PrintCommand2TawkNow(PLGitem *iTEM);
int PrintCommand3TawkNow(PLGitem *iTEM);
int PrintCommandTawkNow(PLGitem *iTEM);
int PrintItem2TawkNow(PLGitem *iTEM);
int PrintShortcutTawkNow(PLGitem *iTEM);
int PrintTawkNow(PLGitem *iTEM);
int QualifiedTawkNow(PLGitem *iTEM);
int QualifyStartTawkNow(PLGitem *iTEM);
int QuestionTawkNow(PLGitem *iTEM);
int QuoteTawkNow(PLGitem *iTEM);
int RangeExpressionTawkNow(PLGitem *iTEM);
int RangeFieldTawkNow(PLGitem *iTEM);
int ResetTypeTawkNow(PLGitem *iTEM);
int SaveVirtualsTawkNow(PLGitem *iTEM);
int SecondaryExpression2TawkNow(PLGitem *iTEM);
int SecondaryExpressionTawkNow(PLGitem *iTEM);
int SetObjectTawkNow(PLGitem *iTEM);
int StartTawkNow(PLGitem *iTEM);
int Statement2TawkNow(PLGitem *iTEM);
int StatementBody10TawkNow(PLGitem *iTEM);
int StatementBody11TawkNow(PLGitem *iTEM);
int StatementBody12TawkNow(PLGitem *iTEM);
int StatementBody14TawkNow(PLGitem *iTEM);
int StatementBody15TawkNow(PLGitem *iTEM);
int StatementBody16TawkNow(PLGitem *iTEM);
int StatementBody17TawkNow(PLGitem *iTEM);
int StatementBody18TawkNow(PLGitem *iTEM);
int StatementBody19TawkNow(PLGitem *iTEM);
int StatementBody20TawkNow(PLGitem *iTEM);
int StatementBody21TawkNow(PLGitem *iTEM);
int StatementBody2TawkNow(PLGitem *iTEM);
int StatementBody3TawkNow(PLGitem *iTEM);
int StatementBody4TawkNow(PLGitem *iTEM);
int StatementBody5TawkNow(PLGitem *iTEM);
int StatementBody6TawkNow(PLGitem *iTEM);
int StatementBody7TawkNow(PLGitem *iTEM);
int StatementBody8TawkNow(PLGitem *iTEM);
int StatementBody9TawkNow(PLGitem *iTEM);
int StatementBodyTawkNow(PLGitem *iTEM);
int StopTawkNow(PLGitem *iTEM);
int StringExpression2TawkNow(PLGitem *iTEM);
int StringsTawkNow(PLGitem *iTEM);
void StructureBody2TawkAct(PLGitem *iTEM);
void StructureBodyTawkAct(PLGitem *iTEM);
void StructureItem2TawkAct(PLGitem *iTEM);
void StructureItemTawkAct(PLGitem *iTEM);
void StructureTawkAct(PLGitem *iTEM);
void StructureType2TawkAct(PLGitem *iTEM);
int SwitchTawkNow(PLGitem *iTEM);
int SyntaxExtensions2TawkNow(PLGitem *iTEM);
int Target2TawkNow(PLGitem *iTEM);
int TargetMethodTawkNow(PLGitem *iTEM);
int TargetTawkNow(PLGitem *iTEM);
int TypeListTawkNow(PLGitem *iTEM);
int TypeNameTawkNow(PLGitem *iTEM);
int TypeTawkNow(PLGitem *iTEM);
int UnaryExpression2TawkNow(PLGitem *iTEM);
int UnaryExpressionTawkNow(PLGitem *iTEM);
int UnaryOperator2TawkNow(PLGitem *iTEM);
void assignFailed(PLGtester *t);
void caseLabelFail(PLGtester *t);
void expressPartFailed(PLGtester *t);
void instanceTailFail(PLGtester *t);
